apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-backend
  template:
    metadata:
      labels:
        app: feedback-backend
    spec:
      containers:
        - name: feedback-backend
          image: karnativ/feedback-backend:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/feedbackdb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          ports:
            - containerPort: 8088

---
apiVersion: v1
kind: Service
metadata:
  name: feedback-backend
spec:
  type: ClusterIP
  selector:
    app: feedback-backend
  ports:
    - port: 8088
      targetPort: 8088
